services:
  redis:
    image: redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - karavantruck-network

  nats:
    image: nats:latest
    container_name: nats-server
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: >
      --user ${NATS_USERNAME}
      --pass ${NATS_PASSWORD}
    networks:
      - karavantruck-network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    command:
      - "--collector.otlp.enabled=true"
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14268:14268" # Jaeger HTTP Thrift (optional)
    environment:
      - LOG_LEVEL=debug
    networks:
      - karavantruck-network

networks:
  karavantruck-network:
    driver: bridge