// Package carrier Code generated by swaggo/swag. DO NOT EDIT
package carrier

import "github.com/swaggo/swag"

const docTemplatecarrier = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attachments/file": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attachments"
                ],
                "summary": "Upload attachment",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Visibility of attachment",
                        "name": "visibility",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder to upload attachment",
                        "name": "folder",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.UploadFileResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "413": {
                        "description": "Request entity too large",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/attachments/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attachments"
                ],
                "summary": "Upload image attachment",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Visibility of attachment",
                        "name": "visibility",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder to upload attachment",
                        "name": "folder",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Width of image",
                        "name": "width",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Height of image",
                        "name": "height",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Compress image",
                        "name": "compress",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.UploadImageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "413": {
                        "description": "Request entity too large",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/attachments/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attachments"
                ],
                "summary": "Get attachment metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.AttachmentResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/attachments/{id}/download": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Attachments"
                ],
                "summary": "Download attachment file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/apple": {
            "post": {
                "description": "Authenticate or register a user via Apple ID token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Apple Sign In",
                "parameters": [
                    {
                        "description": "Apple ID token and optional profile fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.AppleSignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.AppleSignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email/phone and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout user (revokes all outstanding refresh tokens)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/pkce": {
            "post": {
                "description": "Generate PKCE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Generate PKCE",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.GeneratePKCEResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new token pair. The body is JSON or a form (the phone's tracking library refreshes with a form), chosen by Content-Type",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new account and send a verification code to the provided email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/telegram": {
            "post": {
                "description": "Authenticate or register a user via a Telegram OIDC id_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Telegram Sign In (OAuth 2.0 / OIDC)",
                "parameters": [
                    {
                        "description": "Telegram OIDC id_token and optional role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.TelegramSignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.TelegramSignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/telegram/callback": {
            "get": {
                "description": "Receives the OAuth redirect from Telegram and bounces the user\nback into the mobile app via a yoollive:// custom URL scheme.",
                "tags": [
                    "Auth"
                ],
                "summary": "Telegram OAuth redirect",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PKCE state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Exchange a Telegram authorization code for app tokens. The code exchange\nis performed server-side so the client secret is never exposed to the browser.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Telegram OAuth (web code exchange)",
                "parameters": [
                    {
                        "description": "Authorization code, redirect_uri and optional role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.TelegramOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.TelegramSignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "description": "Verify the OTP code sent to email and receive access tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "description": "Email and OTP code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.VerifyEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.VerifyEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/carriers/companies/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get company by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "Get company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.CompanyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/invites/{token}": {
            "get": {
                "description": "PUBLIC, unauthenticated preview of a load invite by token. Returns 200 even for expired/accepted/revoked invites so the app can render an explanatory state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites"
                ],
                "summary": "Get invite preview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.GetInviteResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/invites/{token}/accept": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accept the load an invite link points to. The authenticated carrier is assigned to the load (same transition as the shipper-initiated assign flow).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invites"
                ],
                "summary": "Accept a load invite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.AcceptInviteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/leads": {
            "post": {
                "description": "PUBLIC, unauthenticated contact form submission from the marketing landing page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leads"
                ],
                "summary": "Submit sales lead",
                "parameters": [
                    {
                        "description": "Lead form data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.submitLeadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current active load for the authenticated carrier (accepted, in_transit, or completed)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Get active load",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.LoadDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get completed and cancelled loads for the authenticated carrier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Get load history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Get latest assigned load",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.ListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get load by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Get load",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.LoadDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/accept": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accept an assigned load (by carrier)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Accept load",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/dropoff/begin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Carrier arrived at destination (in_transit → dropping_off)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Begin dropoff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/dropoff/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cargo unloaded at destination (dropping_off → dropped_off)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Confirm dropoff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/location": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a GPS location point for an in-transit load (MVP REST alternative to WebSocket)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Register location point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Location data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RegisterLoadLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/location/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Flush GPS points buffered on the phone while offline; each keeps its original recorded_at so the track backfills instead of losing the gap",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Register a batch of location points",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Buffered location points",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RegisterLoadLocationBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/pickup/begin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Carrier is driving to pickup location (accepted → picking_up)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Begin pickup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/pickup/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cargo loaded onto truck (picking_up → picked_up)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Confirm pickup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/loads/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a load (by carrier, transitions to in-transit)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loads"
                ],
                "summary": "Start load",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/public/tracking/{token}": {
            "get": {
                "description": "PUBLIC, unauthenticated snapshot of a load's status and latest known position, by tracking-link token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracking"
                ],
                "summary": "Get public cargo tracking snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tracking link token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.GetPublicTrackingResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/public/tracking/{token}/route": {
            "get": {
                "description": "PUBLIC, unauthenticated route matched to roads, by tracking-link token (same shape as the authenticated GET /loads/{id}/route)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracking"
                ],
                "summary": "Get public cargo route",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tracking link token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.GetRouteResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/public/tracking/{token}/track": {
            "get": {
                "description": "PUBLIC, unauthenticated location history for a load, by tracking-link token, oldest first (same shape and paging as the authenticated GET /loads/{id}/track)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracking"
                ],
                "summary": "Get public cargo tracking history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tracking link token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max number of points (default 500, max 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.GetTrackResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/tracking/locations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a batch of the phone's tracking library records. Each point carries its load_id; points outside their load's tracking window (from acceptance to confirmation, a cancelled load keeps taking them), of other drivers' loads or malformed are dropped, not rejected. Any parsable body gets 200, so the phone can clear its queue; the response's load_status and stop_tracking describe the load of the batch's latest point.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracking"
                ],
                "summary": "Register GPS points from the tracking library",
                "parameters": [
                    {
                        "description": "Tracking library records",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RegisterLocationsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.RegisterLocationsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the profile of the authenticated user (includes role)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/query.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the profile of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update current user",
                "parameters": [
                    {
                        "description": "Update User Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_karavanix_karavantrack-api-server_internal_usecase_users_command.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently deletes the authenticated user's account and all associated data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete current user",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/users/me/devices": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register or update a device for push notifications",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register FCM device",
                "parameters": [
                    {
                        "description": "Device registration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/command.RegisterDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Upgrades HTTP connection to a full-duplex WebSocket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket endpoint for chat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT authentication token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing/invalid headers)",
                        "schema": {
                            "$ref": "#/definitions/outerr.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "command.AcceptInviteResponse": {
            "type": "object",
            "properties": {
                "load_id": {
                    "type": "string"
                }
            }
        },
        "command.AppleSignInRequest": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id_token": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "command.AppleSignInResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the access token's lifetime in seconds.",
                    "type": "integer"
                },
                "is_new_user": {
                    "type": "boolean"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "command.GeneratePKCEResponse": {
            "type": "object",
            "properties": {
                "code_challenge": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "command.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "command.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the access token's lifetime in seconds.",
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "command.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "command.RegisterDeviceRequest": {
            "type": "object",
            "required": [
                "device_id",
                "device_token"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "device_token": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                }
            }
        },
        "command.RegisterLoadLocationBatchPoint": {
            "type": "object",
            "properties": {
                "accuracy_m": {
                    "type": "number"
                },
                "heading_deg": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "recorded_at": {
                    "type": "string"
                },
                "speed_mps": {
                    "type": "number"
                }
            }
        },
        "command.RegisterLoadLocationBatchRequest": {
            "type": "object",
            "properties": {
                "carrier_id": {
                    "type": "string"
                },
                "load_id": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/command.RegisterLoadLocationBatchPoint"
                    }
                }
            }
        },
        "command.RegisterLoadLocationRequest": {
            "type": "object",
            "properties": {
                "accuracy_m": {
                    "type": "number"
                },
                "carrier_id": {
                    "type": "string"
                },
                "heading_deg": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "load_id": {
                    "type": "string"
                },
                "recorded_at": {
                    "type": "string"
                },
                "speed_mps": {
                    "type": "number"
                }
            }
        },
        "command.RegisterLocationsPoint": {
            "type": "object",
            "properties": {
                "accuracy_m": {
                    "type": "number"
                },
                "activity_confidence": {
                    "type": "integer"
                },
                "activity_type": {
                    "type": "string"
                },
                "altitude_m": {
                    "type": "number"
                },
                "battery_level": {
                    "description": "BatteryLevel is a fraction, 0..1.",
                    "type": "number"
                },
                "event": {
                    "description": "Event is \"\" for a regular location.",
                    "type": "string"
                },
                "heading_deg": {
                    "type": "number"
                },
                "is_charging": {
                    "type": "boolean"
                },
                "is_mock": {
                    "type": "boolean"
                },
                "is_moving": {
                    "type": "boolean"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "load_id": {
                    "type": "string"
                },
                "odometer_m": {
                    "type": "number"
                },
                "provider": {
                    "description": "Provider is what Android attaches to a providerchange record.",
                    "type": "object"
                },
                "recorded_at": {
                    "type": "string"
                },
                "speed_mps": {
                    "description": "SpeedMps and HeadingDeg are -1 when unknown.",
                    "type": "number"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "command.RegisterLocationsRequest": {
            "type": "object",
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/command.RegisterLocationsPoint"
                    }
                }
            }
        },
        "command.RegisterLocationsResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "description": "Accepted points were stored (or had already been stored).",
                    "type": "integer"
                },
                "dropped": {
                    "description": "Dropped points are malformed or fall outside their load's tracking\nwindow; they're not coming back, so the phone deletes them all the same.",
                    "type": "integer"
                },
                "load_status": {
                    "description": "LoadStatus is the status of the load of the batch's latest point; null\nwhen that load doesn't exist or isn't this driver's.",
                    "type": "string"
                },
                "stop_tracking": {
                    "description": "StopTracking tells the phone to stop: that load is confirmed,\ncancelled, waiting for a confirmation too long, or not this driver's.",
                    "type": "boolean"
                }
            }
        },
        "command.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "shipper",
                        "carrier"
                    ]
                }
            }
        },
        "command.TelegramOAuthRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "command.TelegramSignInRequest": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "command.TelegramSignInResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the access token's lifetime in seconds.",
                    "type": "integer"
                },
                "is_new_user": {
                    "type": "boolean"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "command.UploadFileResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "publicURL": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "command.UploadImageResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "publicURL": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "command.VerifyEmailRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "command.VerifyEmailResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "ExpiresIn is the access token's lifetime in seconds.",
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "common.submitLeadRequest": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "fleet": {
                    "type": "string"
                },
                "honeypot": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "github_com_karavanix_karavantrack-api-server_internal_usecase_users_command.UpdateRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "outerr.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "query.AttachmentResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "publicURL": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "query.CompanyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "query.ConnectionStatusResponse": {
            "type": "object",
            "properties": {
                "last_point_at": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "query.GetInviteResponse": {
            "type": "object",
            "properties": {
                "accepted_by_me": {
                    "type": "boolean"
                },
                "load": {
                    "$ref": "#/definitions/query.InviteLoadPreview"
                },
                "load_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "query.GetPublicTrackingResponse": {
            "type": "object",
            "properties": {
                "connection": {
                    "$ref": "#/definitions/query.ConnectionStatusResponse"
                },
                "load": {
                    "$ref": "#/definitions/query.PublicTrackingLoad"
                },
                "position": {
                    "$ref": "#/definitions/query.PublicPosition"
                }
            }
        },
        "query.GetRouteResponse": {
            "type": "object",
            "properties": {
                "distance_m": {
                    "description": "DistanceM is the distance driven along roads; gaps aren't counted.",
                    "type": "number"
                },
                "load_id": {
                    "type": "string"
                },
                "matched_until": {
                    "description": "MatchedUntil is when the last point covered by the route was\nrecorded; points after it are drawn raw up to the live marker.",
                    "type": "string"
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/query.RouteSegmentResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "query.GetTrackResponse": {
            "type": "object",
            "properties": {
                "load_id": {
                    "type": "string"
                },
                "points": {
                    "description": "Points are oldest first.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/query.TrackPointResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "query.HistoryAttachmentResponse": {
            "type": "object",
            "properties": {
                "attachment_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "history_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "url": {
                    "description": "URL is best-effort: a public attachment's stable URL, or a short-lived\npresigned URL for a private one. Omitted if it could not be resolved\n(see attachmentURLResolver) — the client still has AttachmentID and can\nfall back to GET /attachments/{id}.",
                    "type": "string"
                }
            }
        },
        "query.HistoryResponse": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/query.HistoryAttachmentResponse"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "from_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "to_status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "query.InviteLoadPreview": {
            "type": "object",
            "properties": {
                "company_name": {
                    "type": "string"
                },
                "dropoff_address": {
                    "type": "string"
                },
                "dropoff_at": {
                    "type": "string"
                },
                "pickup_address": {
                    "type": "string"
                },
                "pickup_at": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "query.ListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/query.LoadResponse"
                    }
                }
            }
        },
        "query.LoadDetailResponse": {
            "type": "object",
            "properties": {
                "carrier_id": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dropoff_address": {
                    "type": "string"
                },
                "dropoff_at": {
                    "type": "string"
                },
                "dropoff_lat": {
                    "type": "number"
                },
                "dropoff_lng": {
                    "type": "number"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/query.HistoryResponse"
                    }
                },
                "id": {
                    "type": "string"
                },
                "member_id": {
                    "type": "string"
                },
                "pickup_address": {
                    "type": "string"
                },
                "pickup_at": {
                    "type": "string"
                },
                "pickup_lat": {
                    "type": "number"
                },
                "pickup_lng": {
                    "type": "number"
                },
                "reference_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "query.LoadResponse": {
            "type": "object",
            "properties": {
                "carrier_id": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dropoff_address": {
                    "type": "string"
                },
                "dropoff_at": {
                    "type": "string"
                },
                "dropoff_lat": {
                    "type": "number"
                },
                "dropoff_lng": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "member_id": {
                    "type": "string"
                },
                "pickup_address": {
                    "type": "string"
                },
                "pickup_at": {
                    "type": "string"
                },
                "pickup_lat": {
                    "type": "number"
                },
                "pickup_lng": {
                    "type": "number"
                },
                "reference_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "query.MeResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "query.PublicPosition": {
            "type": "object",
            "properties": {
                "heading_deg": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "recorded_at": {
                    "type": "string"
                },
                "speed_mps": {
                    "type": "number"
                }
            }
        },
        "query.PublicTrackPoint": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "at": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "query.PublicTrackingLoad": {
            "type": "object",
            "properties": {
                "dropoff": {
                    "$ref": "#/definitions/query.PublicTrackPoint"
                },
                "pickup": {
                    "$ref": "#/definitions/query.PublicTrackPoint"
                },
                "reference_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "query.RouteSegmentResponse": {
            "type": "object",
            "properties": {
                "distance_m": {
                    "type": "number"
                },
                "ended_at": {
                    "type": "string"
                },
                "geometry": {
                    "description": "Geometry is a polyline6 string (@mapbox/polyline, precision 6).",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind: matched (along roads, solid line), raw (the matcher couldn't\nplace it: raw GPS line, thin), gap (no data: straight dashed line),\nstop (a single point: stop marker).",
                    "type": "string",
                    "enum": [
                        "matched",
                        "raw",
                        "gap",
                        "stop"
                    ]
                },
                "started_at": {
                    "type": "string"
                }
            }
        },
        "query.TrackPointResponse": {
            "type": "object",
            "properties": {
                "accuracy_m": {
                    "type": "number"
                },
                "heading_deg": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "recorded_at": {
                    "type": "string"
                },
                "speed_mps": {
                    "type": "number"
                },
                "status_event": {
                    "$ref": "#/definitions/query.TrackStatusEvent"
                }
            }
        },
        "query.TrackStatusEvent": {
            "type": "object",
            "properties": {
                "from_status": {
                    "type": "string"
                },
                "history_id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "to_status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "API Токен используется для авторизации",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfocarrier holds exported Swagger Info so clients can modify it
var SwaggerInfocarrier = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Carriers API",
	Description:      "",
	InfoInstanceName: "carrier",
	SwaggerTemplate:  docTemplatecarrier,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocarrier.InstanceName(), SwaggerInfocarrier)
}
